// <auto-generated />
namespace timeManager3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class employetest5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(employetest5));
        
        string IMigrationMetadata.Id
        {
            get { return "202101080107193_employetest5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
